export interface CountryData {
  slug: string;          // lowercase-hyphenated, matches URL — e.g. 'usa'
  name: string;          // prepositional display form, reads after "in " — e.g. 'the USA', 'Canada'
  country: string;       // plain country name for schema — e.g. 'United States'
  region: string;        // 'North America', 'Middle East', etc.
  currencyCode: string;  // 'USD'
  hreflang: string;      // regional English code for the hreflang cluster — e.g. 'en-US'
  dialCode: string;      // international dialling prefix, pre-filled in the enquiry form — e.g. '+1'
  approxStart: string;   // approx local value of the ₹1,299 starting plan — e.g. '$15'
  timezoneNote: string;  // how sessions are scheduled relative to IST
  diaspora: string;      // Indian-origin population, phrased directionally
  hubs: string[];        // major cities/areas with large Indian communities
  angle: string;         // one lifestyle hook specific to Indians living there
}

export const COUNTRIES: CountryData[] = [
  {
    slug: 'usa',
    name: 'the USA',
    country: 'United States',
    region: 'North America',
    currencyCode: 'USD',
    hreflang: 'en-US',
    dialCode: '+1',
    approxStart: '$15',
    timezoneNote: 'US time zones (about 9.5–13.5 hours behind IST), so sessions are scheduled for your early morning or evening',
    diaspora: 'over 4.8 million people of Indian origin',
    hubs: ['New Jersey', 'California', 'Texas', 'New York'],
    angle: 'Long desk hours, oversized restaurant portions and a car-first lifestyle make weight gain common for Indians settling in America.',
  },
  {
    slug: 'canada',
    name: 'Canada',
    country: 'Canada',
    region: 'North America',
    currencyCode: 'CAD',
    hreflang: 'en-CA',
    dialCode: '+1',
    approxStart: 'C$21',
    timezoneNote: 'Canadian time zones (about 9.5–13.5 hours behind IST), with sessions set for your convenient hours',
    diaspora: 'more than 1.4 million people of Indian origin',
    hubs: ['Toronto', 'Brampton', 'Vancouver', 'Calgary'],
    angle: 'Long, harsh winters keep people indoors for months, making a structured home-workout routine essential for many Indian-Canadians.',
  },
  {
    slug: 'uk',
    name: 'the UK',
    country: 'United Kingdom',
    region: 'Europe',
    currencyCode: 'GBP',
    hreflang: 'en-GB',
    dialCode: '+44',
    approxStart: '£13',
    timezoneNote: 'UK time (about 4.5–5.5 hours behind IST), so live sessions fit neatly into your day',
    diaspora: 'around 1.9 million people of Indian origin',
    hubs: ['London', 'Leicester', 'Birmingham', 'Manchester'],
    angle: 'A busy work culture and a pub-and-takeaway food scene make consistency the biggest challenge for Indians in Britain.',
  },
  {
    slug: 'ireland',
    name: 'Ireland',
    country: 'Ireland',
    region: 'Europe',
    currencyCode: 'EUR',
    hreflang: 'en-IE',
    dialCode: '+353',
    approxStart: '€14',
    timezoneNote: 'Irish time (about 4.5–5.5 hours behind IST), with sessions scheduled around your work hours',
    diaspora: 'a fast-growing Indian community',
    hubs: ['Dublin', 'Cork', 'Galway', 'Limerick'],
    angle: 'Long office hours and limited access to familiar Indian ingredients make personalised online coaching genuinely valuable.',
  },
  {
    slug: 'uae',
    name: 'the UAE',
    country: 'United Arab Emirates',
    region: 'Middle East',
    currencyCode: 'AED',
    hreflang: 'en-AE',
    dialCode: '+971',
    approxStart: '57 AED',
    timezoneNote: 'Gulf Standard Time (just 1.5 hours behind IST), so scheduling live sessions is effortless',
    diaspora: 'roughly 3.5 million Indians — the largest expatriate community in the country',
    hubs: ['Dubai', 'Abu Dhabi', 'Sharjah', 'Ajman'],
    angle: 'Extreme summer heat pushes workouts indoors, and a rich dining-out culture makes portion control the key focus for Indian expats in the Gulf.',
  },
  {
    slug: 'saudi-arabia',
    name: 'Saudi Arabia',
    country: 'Saudi Arabia',
    region: 'Middle East',
    currencyCode: 'SAR',
    hreflang: 'en-SA',
    dialCode: '+966',
    approxStart: '59 SAR',
    timezoneNote: 'Arabia Standard Time (about 2.5 hours behind IST), making live coaching easy to schedule',
    diaspora: 'over 2.5 million Indian workers and professionals',
    hubs: ['Riyadh', 'Jeddah', 'Dammam', 'Al Khobar'],
    angle: 'Hot weather and demanding work schedules make flexible, home-friendly online coaching ideal for Indian professionals in the Kingdom.',
  },
  {
    slug: 'qatar',
    name: 'Qatar',
    country: 'Qatar',
    region: 'Middle East',
    currencyCode: 'QAR',
    hreflang: 'en-QA',
    dialCode: '+974',
    approxStart: '57 QAR',
    timezoneNote: 'Arabia Standard Time (about 2.5 hours behind IST), so sessions slot easily into your routine',
    diaspora: 'around 800,000 Indians — one of the largest communities in the country',
    hubs: ['Doha', 'Al Rayyan', 'Al Wakrah'],
    angle: 'Long work weeks and a dining-heavy social scene make structured nutrition the top priority for Indian expats in Doha.',
  },
  {
    slug: 'kuwait',
    name: 'Kuwait',
    country: 'Kuwait',
    region: 'Middle East',
    currencyCode: 'KWD',
    hreflang: 'en-KW',
    dialCode: '+965',
    approxStart: '5 KWD',
    timezoneNote: 'Arabia Standard Time (about 2.5 hours behind IST), with sessions set for your free hours',
    diaspora: 'close to 1 million Indians — the largest expatriate group',
    hubs: ['Kuwait City', 'Hawalli', 'Salmiya'],
    angle: 'Desert heat and desk-bound jobs make an at-home, coach-guided routine the most practical path for Indians in Kuwait.',
  },
  {
    slug: 'australia',
    name: 'Australia',
    country: 'Australia',
    region: 'Oceania',
    currencyCode: 'AUD',
    hreflang: 'en-AU',
    dialCode: '+61',
    approxStart: 'A$25',
    timezoneNote: 'Australian time zones (about 4.5–5.5 hours ahead of IST), so sessions fit your mornings or evenings',
    diaspora: 'nearly 1 million people of Indian origin',
    hubs: ['Sydney', 'Melbourne', 'Brisbane', 'Perth'],
    angle: 'An active outdoor culture is a great fit, but shift work and frequent eating out still make expert guidance valuable for Indian-Australians.',
  },
  {
    slug: 'new-zealand',
    name: 'New Zealand',
    country: 'New Zealand',
    region: 'Oceania',
    currencyCode: 'NZD',
    hreflang: 'en-NZ',
    dialCode: '+64',
    approxStart: 'NZ$26',
    timezoneNote: 'New Zealand time (about 6.5–7.5 hours ahead of IST), with sessions scheduled to suit you',
    diaspora: 'a large and growing Indian community of around 240,000',
    hubs: ['Auckland', 'Wellington', 'Hamilton', 'Christchurch'],
    angle: 'A relaxed outdoor lifestyle pairs perfectly with structured online coaching for Indians settling in New Zealand.',
  },
  {
    slug: 'singapore',
    name: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    currencyCode: 'SGD',
    hreflang: 'en-SG',
    dialCode: '+65',
    approxStart: 'S$21',
    timezoneNote: 'Singapore Standard Time (about 2.5 hours ahead of IST), so live sessions are simple to arrange',
    diaspora: 'a large Indian community of over 650,000',
    hubs: ['Singapore'],
    angle: 'Hawker-centre food culture and demanding corporate hours make macro-aware meal planning essential for Indians in Singapore.',
  },
  {
    slug: 'oman',
    name: 'Oman',
    country: 'Oman',
    region: 'Middle East',
    currencyCode: 'OMR',
    hreflang: 'en-OM',
    dialCode: '+968',
    approxStart: '6 OMR',
    timezoneNote: 'Gulf Standard Time (just 1.5 hours behind IST), so live sessions fit your evenings with no awkward hours',
    diaspora: 'over 600,000 Indians — the largest expatriate community in the Sultanate',
    hubs: ['Muscat', 'Sohar', 'Salalah', 'Sur'],
    angle: 'Long summers spent indoors, a car-first daily routine and generous Omani-Indian hospitality make a coach-guided home routine and portion plan the practical fix for Indians in Oman.',
  },
  {
    slug: 'bahrain',
    name: 'Bahrain',
    country: 'Bahrain',
    region: 'Middle East',
    currencyCode: 'BHD',
    hreflang: 'en-BH',
    dialCode: '+973',
    approxStart: '6 BHD',
    timezoneNote: 'Arabia Standard Time (about 2.5 hours behind IST), making live coaching easy to schedule after work',
    diaspora: 'around 350,000 Indians — close to a quarter of the island’s population',
    hubs: ['Manama', 'Riffa', 'Muharraq', 'Isa Town'],
    angle: 'A compact island with a busy dining-out scene and hot, humid summers: the Indian community in Bahrain does best with indoor training and a nutrition plan built around what is actually on the table.',
  },
  {
    slug: 'malaysia',
    name: 'Malaysia',
    country: 'Malaysia',
    region: 'Asia',
    currencyCode: 'MYR',
    hreflang: 'en-MY',
    dialCode: '+60',
    approxStart: 'RM 65',
    timezoneNote: 'Malaysia Time (about 2.5 hours ahead of IST), so live sessions slot easily into your evening',
    diaspora: 'more than 2 million Malaysians of Indian origin, one of the largest Indian communities outside India',
    hubs: ['Kuala Lumpur', 'Penang', 'Johor Bahru', 'Ipoh'],
    angle: 'Round-the-clock mamak stalls, roti canai breakfasts and year-round humidity make calorie-aware Indian meal planning the biggest lever for Malaysian Indians.',
  },
  {
    slug: 'south-africa',
    name: 'South Africa',
    country: 'South Africa',
    region: 'Africa',
    currencyCode: 'ZAR',
    hreflang: 'en-ZA',
    dialCode: '+27',
    approxStart: 'R270',
    timezoneNote: 'South Africa Standard Time (about 3.5 hours behind IST), so sessions fit your early morning or evening',
    diaspora: 'around 1.5 million South Africans of Indian origin, the largest Indian community in Africa',
    hubs: ['Durban', 'Johannesburg', 'Pretoria', 'Cape Town'],
    angle: 'Braai weekends, rich Durban curries and a community with some of the country’s highest rates of diabetes and heart disease make heart-smart Indian nutrition and strength training especially valuable.',
  },
  {
    slug: 'germany',
    name: 'Germany',
    country: 'Germany',
    region: 'Europe',
    currencyCode: 'EUR',
    hreflang: 'en-DE',
    dialCode: '+49',
    approxStart: '€14',
    timezoneNote: 'Central European Time (about 3.5–4.5 hours behind IST), so live sessions fit your evening after work',
    diaspora: 'a fast-growing Indian community of over 250,000, led by IT professionals and students',
    hubs: ['Berlin', 'Munich', 'Frankfurt', 'Hamburg'],
    angle: 'Bread-and-cheese lunches, long dark winters and limited Indian groceries outside the big cities make a coach who plans around German supermarkets and your home kitchen genuinely useful.',
  },
  {
    slug: 'netherlands',
    name: 'the Netherlands',
    country: 'Netherlands',
    region: 'Europe',
    currencyCode: 'EUR',
    hreflang: 'en-NL',
    dialCode: '+31',
    approxStart: '€14',
    timezoneNote: 'Central European Time (about 3.5–4.5 hours behind IST), with sessions scheduled around your work day',
    diaspora: 'a large Indian community, including the Surinamese-Hindustani diaspora, of over 250,000',
    hubs: ['Amsterdam', 'Amstelveen', 'The Hague', 'Eindhoven'],
    angle: 'Daily cycling is a head start, but bread-based lunches, long grey winters and expat work hours still make structured strength training and Indian meal planning the difference for Indians in the Netherlands.',
  },
  {
    slug: 'hong-kong',
    name: 'Hong Kong',
    country: 'Hong Kong',
    region: 'Asia',
    currencyCode: 'HKD',
    hreflang: 'en-HK',
    dialCode: '+852',
    approxStart: 'HK$120',
    timezoneNote: 'Hong Kong Time (about 2.5 hours ahead of IST), so live sessions fit comfortably into your evening',
    diaspora: 'an Indian community of around 40,000, many in finance, trading and hospitality',
    hubs: ['Tsim Sha Tsui', 'Kowloon', 'Hong Kong Island', 'Discovery Bay'],
    angle: 'Long finance hours, tiny flats with no room for equipment and a dining-out culture make compact bodyweight training and portion-smart Indian meals the realistic route for Indians in Hong Kong.',
  },
  {
    slug: 'japan',
    name: 'Japan',
    country: 'Japan',
    region: 'Asia',
    currencyCode: 'JPY',
    hreflang: 'en-JP',
    dialCode: '+81',
    approxStart: '¥2,200',
    timezoneNote: 'Japan Standard Time (about 3.5 hours ahead of IST), so live sessions fit your evening after work',
    diaspora: 'a growing Indian community of around 50,000, concentrated among IT professionals',
    hubs: ['Tokyo', 'Nishi-Kasai', 'Yokohama', 'Osaka'],
    angle: 'Long office hours, convenience-store meals and the challenge of finding vegetarian protein make a coach who plans Indian meals from Japanese supermarket staples a real advantage.',
  },
  {
    slug: 'mauritius',
    name: 'Mauritius',
    country: 'Mauritius',
    region: 'Africa',
    currencyCode: 'MUR',
    hreflang: 'en-MU',
    dialCode: '+230',
    approxStart: 'Rs 690',
    timezoneNote: 'Mauritius Time (just 1.5 hours behind IST), so live sessions are effortless to schedule',
    diaspora: 'a population that is close to 70% Indian-origin, with deep cultural ties to India',
    hubs: ['Port Louis', 'Quatre Bornes', 'Curepipe', 'Vacoas'],
    angle: 'Rice- and dholl-puri-heavy meals and one of the world’s highest rates of type 2 diabetes make blood-sugar-aware Indian nutrition and regular strength training a priority for Mauritians.',
  },
];

export function getCountryBySlug(slug: string): CountryData | undefined {
  return COUNTRIES.find(country => country.slug === slug);
}

export function getAllCountrySlugs(): string[] {
  return COUNTRIES.map(country => country.slug);
}

/** hreflang map shared by the hub and every country page (the cluster must be
 *  reciprocal — each page lists all of them). The hub is the x-default. */
export function countryHreflangs(): Record<string, string> {
  const map: Record<string, string> = { 'x-default': 'https://coachhimanshu.com/online-fitness-coach' };
  for (const c of COUNTRIES) map[c.hreflang] = `https://coachhimanshu.com/online-fitness-coach/${c.slug}`;
  return map;
}
